### PR TITLE
add headers: compare, concepts, cstdarg, climits, cfloat. update headers: type_traits, utility, new, memory and algorithm

### PR DESCRIPTION
**Pull request by ilobilo**
this pr adds new headers:
* cstdarg
* climits
* cfloat
* cinttypes
* compare
  - partial_ordering
  - weak_ordering
  - strong_ordering
  - common_comparison_category
  - common_comparison_category_t
  - compare_three_way_result
  - compare_three_way_result_t
  - compare_three_way
  - is_eq
  - is_neq
  - is_lt
  - is_lteq
  - is_gt
  - is_gteq
* concepts
  - same_as
  - derived_from
  - convertible_to
  - integral
  - signed_integral
  - unsigned_integral
  - floating_point
  - boolean_testable
  - __WeaklyEqualityComparableWith
  - equality_comparable
  - __PartiallyOrderedWith
  - totally_ordered
  - __ComparesAs
  - three_way_comparable
  - invocable
  - regular_invocable
  - predicate
  - relation
  - equivalence_relation
  - strict_weak_order

and modified this headers:
* memory
  - allocator
* algorithm
  - min/max constexpr
* new
  - align_val_t
  - destroying_delete_t
  - destroying_delete
* utility
  - piecewise_construct_t
  - piecewise_construct
  - in_place_t
  - in_place_type_t
  - in_place_index_t
* type_traits
  - aligned_storage
  - remove_cv_t
  - add_cv
  - add_cv_t
  - is_void_v
  - is_null_pointer
  - is_null_pointer_v
  - remove_const_t
  - remove_volatile_t
  - add_const
  - add_const_t
  - add_volatile
  - add_volatile_t
  - is_trivially_default_constructible
  - is_trivially_default_constructible_v
  - remove_all_extents
  - remove_all_extents_t
  - is_array_v
  - is_union
  - is_union_v
  - is_class
  - is_class_v
  - is_const_v
  - is_reference_v
  - is_lvalue_reference
  - is_lvalue_reference_v
  - is_rvalue_reference
  - is_rvalue_reference_v
  - is_member_function_pointer_helper
  - is_member_function_pointer
  - is_member_pointer_helper
  - is_member_pointer
  - is_member_object_pointer
  - is_member_object_pointer_v
  - is_fundamental
  - is_fundamental_v
  - is_scalar
  - is_scalar_v
  - is_object
  - is_object_v
  - is_compound
  - is_compound_v
  - is_volatile
  - is_volatile_v
  - is_trivial
  - is_trivial_v
  - is_standard_layout
  - is_standard_layout_v
  - has_unique_object_representations
  - has_unique_object_representations_v
  - is_empty
  - is_empty_v
  - is_polymorphic
  - is_polymorphic_v
  - is_abstract
  - is_abstract_v
  - is_final
  - is_final_v
  - is_aggregate
  - is_aggregate_v
  - is_bounded_array
  - is_bounded_array_v
  - is_unbounded_array
  - is_unbounded_array_v
  - conjunction
  - conjunction_v
  - disjunction
  - disjunction_v
  - negation
  - negation_v
  - is_scoped_enum
  - is_scoped_enum_v
  - alignment_of
  - alignment_of_v
  - rank
  - rank_v
  - extent
  - extent_v
  - is_base_of
  - is_base_of_v
  - is_convertible
  - is_convertible_v
  - is_nothrow_convertible
  - is_nothrow_convertible_v
  - aligned_union
  - aligned_union_t
  - decay_t
  - remove_cvref
  - remove_cvref_t
  - is_constant_evaluated
  - common_reference // TODO: Only partially implemented
  - common_reference_t
  - basic_common_reference

### CODE REVIEW

**Comment by ArsenArsen** [comment]
This includes a bunch of unrelated changes, a megacommit, and code we can't use? (how else did that comment get in there?)

Where does this code come from?

**Comment by ilobilo** [comment]
> Where does this code come from?

I went through all the classes, structs and concepts on cppreference, if there was a "possible implementation" provided, I copied it, if not, I made my own.

That comment was from my kernel, where I copied <compare> from.
Then I thought that including gnu code in cxxshim was a bad idea so I removed all of it (but missed the comment) and wrote my own.

**Comment by avdgrinten** [comment]
Code snippets from cppreference.com are problematic if they are non-trivial. They are CC-BY-SA, but CC-BY-SA and MIT are not compatible.

**Comment by avdgrinten** [comment]
In this case, however, it might be that the snippets are small enough to not be copyrightable.

**Comment by ilobilo** [comment]
@ArsenArsen splitted it into multiple commits

**Comment by ilobilo** [comment]
will this be merged?

**Pull request closed without merging**
